Feat button component
betagouv/ngx-dsfr pull request #2
Opened 2022-07-25 13:53 UTC by abdelazizsakhi

- adding tslint properties

2022-07-26 09:45 UTC, flowg reviewed
Why is there a `yarn.lock` ? I thought we were going with NPM...
I actually have no problem with that but I'm afraid there might be some issues down the line... maybe they don't resolve dependencies the same way on some very obscure use-cases...
Am I being paranoid or ... ?

2022-07-26 11:01 UTC, flowg requested changes

2022-07-26 11:01 UTC, flowg commented on libs/ngx-dsfr/button/src/lib/testing/button.component.spec.ts
> +    describe(' and inline is set to false, ', () => {
I don't see any reason to add a level of separation per use-case for this Component. So we should be able to make it with only 1 nested `describe`, the one for ' all required properties are provided, '.

Therefore, I suggest you merge the `beforeEach` of lines 73 and 79.

For the rest of the test cases, you can pretty much follow what I did for the `DsfrLinkComponent` and adapt. For instance, there should be a unit test testing what happens when a consumer wants to use icons with this Component, etc.

2022-07-28 13:30 UTC, abdelazizsakhi commented on .eslintrc.json
> +              {
It's just some properties that i judge necessary but you can challenge it or we can modify it together.

2022-08-01 09:15 UTC, flowg requested changes

2022-08-01 09:15 UTC, flowg commented on libs/ngx-dsfr/button/src/lib/testing/button.component.spec.ts
> +  const testIcon = 'fr-icon-checkbox-circle-line'
`const testIcon = 'checkbox-circle-line';`

At this level, should be just the name of the icon, not the CSS class that the DSFR expects.

2022-08-01 09:15 UTC, flowg commented on libs/ngx-dsfr/button/src/lib/testing/button.component.spec.ts
> + * 3rd imports
`3rd-party imports` 😉

2022-08-01 09:15 UTC, flowg commented on libs/ngx-dsfr/button/src/lib/testing/button.component.spec.ts
> +    it('should set title identic to label when no title provided', async () => {
'identical'

2022-08-01 09:15 UTC, flowg commented on libs/ngx-dsfr/button/src/lib/testing/button.component.spec.ts
> +      const label: string | null = await (dsfrButtonHarness.getButtonText());
Extra parentheses not necessary

2022-08-01 09:15 UTC, flowg commented on libs/ngx-dsfr/button/src/lib/testing/button.component.spec.ts
> +      expect(title).toContain(label);
More like `.toBe()` ?

2022-08-01 09:19 UTC, flowg commented on .eslintrc.json
> +              {
Ok, we'll see about it if and when it poses a problem 😉

2022-08-01 14:11 UTC, flowg approved these changes

2022-08-01 14:11 UTC, merged