feat(input): add input documentation
betagouv/ngx-dsfr pull request #38
Opened 2023-02-07 17:29 UTC by abdelazizsakhi

2023-04-11 18:17 UTC, flowg requested changes

2023-04-13 08:58 UTC, flowg commented on apps/playground/src/app/modules/components/input-module/input-module.component.html
> +    The <code>DsfrInputComponent</code> purpose is to represent the input form field
Not done

2023-04-13 10:18 UTC, flowg requested changes

2023-04-14 00:52 UTC, abdelazizsakhi commented on apps/playground/src/app/modules/components/input-module/input-module.component.ts
> +    this.handleErrors('Please, enter a failure meessage for this Component', 'failureMessage');
Can we fix this together, the component reacts very strangely

2023-04-14 15:16 UTC, flowg requested changes

2023-04-14 15:16 UTC, flowg commented on apps/playground/src/app/modules/components/input-module/input-module.component.ts
> +      'Please, enter a failure meessage for this Component if the hasFailed attribute is true'
`failure message`

2023-04-14 15:16 UTC, flowg commented on apps/playground/src/app/modules/components/input-module/input-module.component.ts
> +    label: ['This is a label', Validators.required],
Here, only `label` needs to be `required`

2023-04-17 11:45 UTC, flowg approved these changes

2023-04-17 13:21 UTC, merged