feat(input text): input component
betagouv/ngx-dsfr pull request #9
Opened 2022-10-21 10:53 UTC by abdelazizsakhi

2022-10-26 20:07 UTC, flowg requested changes

2022-10-26 20:07 UTC, flowg commented on libs/ngx-dsfr/input/src/lib/testing/input.harness.ts
> +    const attributes = await input.getAttribute(name);
`attribute` without an 's' seems more appropriate, don't you think ?

2022-10-26 20:07 UTC, flowg commented on libs/ngx-dsfr/input/src/lib/testing/input.harness.ts
> +   * @returns A Promise that resolves to the name values as a strings or null
For all the comments : it's `input tag` and `value as a string`

2022-10-26 20:07 UTC, flowg commented on libs/ngx-dsfr/input/src/lib/testing/input.component.spec.ts
> +  let dsfrRadioHarness: DsfrInputHarness;
`dsfrInputHarness`

2022-10-26 20:07 UTC, flowg commented on libs/ngx-dsfr/input/src/lib/testing/input.component.spec.ts
> +  });
Can be easily adapted to add the same check for `label` once `Id` is provided

2022-10-26 20:07 UTC, flowg commented on libs/ngx-dsfr/input/src/lib/input.component.ts
> +    }
It's `label` and not `placeholder` that should be checked here...

2022-11-03 13:38 UTC, abdelazizsakhi commented on libs/ngx-dsfr/input/src/lib/input.component.html
> +        [disabled]="disabled ? 'disabled' : false"
Nope, it is not working with `[disabled]="disabled"`

2022-11-03 14:44 UTC, flowg commented on apps/playground/src/app/modules/components/link-module/link-module.component.ts
> +  formInlineTrue: FormGroup<any> | undefined;
Why did you change that ?

2022-11-03 14:44 UTC, flowg commented on libs/ngx-dsfr/input/src/lib/input.component.html
> +      <div [ngClass]="icon ? 'fr-input-wrap ' + icon : ''">
Not treated

2022-11-03 14:44 UTC, flowg commented on libs/ngx-dsfr/input/src/lib/input.component.html
>          [ngClass]="{'fr-input--error': hasFailed, 'fr-input--valid': hasSucceeded}"
For consistency, same remark here on how to handle classes depending on Component logic and Input properties

2022-11-03 14:44 UTC, flowg commented on libs/ngx-dsfr/input/src/lib/testing/input.harness.ts
> +  private getInputElement: AsyncFactoryFn<TestElement> = this.locatorFor('input[type=text]');
Not treated

2022-11-03 14:44 UTC, flowg commented on libs/ngx-dsfr/input/src/lib/testing/input.harness.ts
> +   * @returns A Promise that resolves to the name values as a strings or null
Not treated

2022-11-03 14:48 UTC, flowg requested changes

2022-11-03 14:48 UTC, flowg commented on libs/ngx-dsfr/stepper/src/lib/stepper.component.scss
> + // @use "@gouvfr/dsfr/dist/component/stepper/stepper.min";
Why did you change that ?

2022-11-03 15:35 UTC, merged